trigger:
- main

resources:
- repo: self

variables:
  # Azure Container Registry connection established during pipeline creation
  dockerRegistryServiceConnection: 'acr-sc-token'
  # Docker Hub repository name
  dockerHubRepository: 'darksaber8888/timetable.app'
  # ACR repository name
  acrRepository: 'timetableapp.azurecr.io/timetable.app:v2'
  # Snyk token
  snykToken: 'ydckr_pat_IpYiEhNrkDYkiOnduNQhBumuvDg'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build_and_Scan
    displayName: Build, Scan, and Push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-sc'
        command: 'login'
    
    - task: CmdLine@2
      inputs:
        script: 'docker image pull darksaber8888/timetable.app:v2'

    - task: SnykSecurityScan@1
      inputs:
        serviceConnectionEndpoint: 'snykToken'
        testType: 'container'
        dockerImageName: 'darksaber8888/timetable.app:v2'
        monitorWhen: 'always'
        failOnIssues: false
    - task: Docker@2
      displayName: Tag Docker image for ACR
      inputs:
        command: tag
        arguments: '$(dockerHubRepository) $(acrRepository)'

    - task: Docker@2
      displayName: Push Docker image to ACR
      inputs:
        command: push
        repository: $(acrRepository)
        containerRegistry: $(dockerRegistryServiceConnection)

