trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'acr-sc-token'
  imageRepository: 'timetableapp'
  containerRegistry: 'timetableapp.azurecr.io'
  dockerfilePath: 'Dockerfile'  # Assuming Dockerfile is in the root directory of the repository
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
      fetchDepth: 1  # Fetch only one commit to speed up checkout
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          workingDirectory: '$(System.DefaultWorkingDirectory)'  # Set the working directory to the directory where Git artifacts were downloaded
