apiVersion: apps/v1
kind: Deployment
metadata:
  name: timetable-app-deployment
  labels:
    app: timetable-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timetable-app
  template:
    metadata:
      labels:
        app: timetable-app
    spec:
      containers:
      - name: timetable-app-container
        image: capstoneapp.azurecr.io/timetableapp:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: timetable-app-service
spec:
  selector:
    app: timetable-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
